AUTO_ADD_GLOBAL_DEFINE_BY_NAME = MTK_LCA_SUPPORT MTK_WAPI_SUPPORT MTK_SENSOR_SUPPORT CUSTOM_KERNEL_ALSPS CUSTOM_KERNEL_MAGNETOMETER CUSTOM_KERNEL_ACCELEROMETER MTK_TVOUT_SUPPORT MTK_BT_SUPPORT MTK_FM_SUPPORT MTK_CAMERA_APP_3DHW_SUPPORT MTK_QVGA_LANDSCAPE_SUPPORT MTK_WLANBT_SINGLEANT MTK_FM_TX_SUPPORT MTK_VT3G324M_SUPPORT MTK_M4U_SUPPORT MTK_MATV_ANALOG_SUPPORT MTK_WLAN_SUPPORT MTK_BT_21_SUPPORT MTK_BT_30_SUPPORT MTK_BT_40_SUPPORT MTK_BT_FM_OVER_BT_VIA_CONTROLLER MTK_BT_PROFILE_OPP MTK_BT_PROFILE_SIMAP MTK_BT_PROFILE_PRXM MTK_BT_PROFILE_PRXR MTK_BT_PROFILE_HIDH MTK_BT_PROFILE_FTP MTK_BT_PROFILE_PBAP MTK_BT_PROFILE_MANAGER MTK_BT_PROFILE_BPP MTK_BT_PROFILE_BIP MTK_BT_PROFILE_DUN MTK_BT_PROFILE_PAN MTK_BT_PROFILE_HFP MTK_BT_PROFILE_A2DP MTK_BT_PROFILE_AVRCP MTK_BT_PROFILE_AVRCP14 MTK_BT_PROFILE_TIMEC MTK_BT_PROFILE_TIMES MTK_BT_PROFILE_MAPS MTK_BT_PROFILE_MAPC MTK_BT_PROFILE_SPP MTK_FM_SHORT_ANTENNA_SUPPORT MTK_DUAL_MIC_SUPPORT MTK_WIFI_HOTSPOT_SUPPORT MTK_CTA_SUPPORT MTK_FM_SUPPORT MTK_GPS_SUPPORT MTK_DSPIRDBG HAVE_XLOG_FEATURE MTK_AUTO_DETECT_MAGNETOMETER MTK_AUTO_DETECT_ACCELEROMETER MTK_MAV_SUPPORT MTK_HDR_SUPPORT MTK_CAMERA_BSP_SUPPORT MTK_AUTORAMA_SUPPORT MTK_IPV6_SUPPORT MTK_MULTI_STORAGE_SUPPORT MTK_FM_RECORDING_SUPPORT MTK_USES_HD_VIDEO MTK_NFC_SUPPORT MTK_THEMEMANAGER_APP MTK_BRAZIL_CUSTOMIZATION MTK_BRAZIL_CUSTOMIZATION_CLARO MTK_BRAZIL_CUSTOMIZATION_VIVO MTK_RMVB_PLAYBACK_SUPPORT MTK_ASF_PLAYBACK_SUPPORT MTK_EMMC_SUPPORT MTK_HDMI_SUPPORT MODEM_UMTS_TDD128_MODE MTK_EAP_SIM_AKA MTK_FACEBEAUTY_SUPPORT MTK_FM_RX_SUPPORT MTK_TB_DEBUG_SUPPORT MTK_FAN5405_SUPPORT MTK_COMBO_SUPPORT MTK_CAMCORDER_PROFILE_MID_MP4 MTK_DISPLAY_HIGH_RESOLUTION MTK_FD_SUPPORT MTK_MASS_STORAGE MTK_FM_50KHZ_SUPPORT MTK_EMMC_SUPPORT_OTP MTK_2SDCARD_SWAP MTK_SD_REINIT_SUPPORT CUSTOM_KERNEL_CCCI HQ_PROJECT_A61P_HUAWEI HQ_CHARGER_FOR_HUAWEI  MTK_BICR_SUPPORT CONSTANT_FLASHLIGHT MT9P017_MIPI_RAW S5K4E1GA_MIPI_RAW HI704_YUV GC0329_YUV CONFIG_MTK_USB_UNIQUE_SERIAL MTK_CPU_TEST_MODE_FORCE USER_BUILD_KERNEL

AUTO_ADD_GLOBAL_DEFINE_BY_VALUE = MTK_PLATFORM MTK_FM_CHIP MTK_BT_CHIP CUSTOM_KERNEL_MAIN_IMGSENSOR CUSTOM_KERNEL_MAIN_BACKUP_IMGSENSOR CUSTOM_KERNEL_SUB_IMGSENSOR CUSTOM_KERNEL_SUB_BACKUP_IMGSENSOR CUSTOM_KERNEL_MAIN_LENS CUSTOM_KERNEL_MAIN_BACKUP_LENS CUSTOM_KERNEL_SUB_LENS CUSTOM_KERNEL_SUB_BACKUP_LENS MTK_ATV_CHIP MTK_GPS_CHIP MTK_WLAN_CHIP MTK_MODEM_SUPPORT CUSTOM_KERNEL_LCM CUSTOM_KERNEL_FLASHLIGHT MTK_FM_TX_AUDIO MTK_FM_RX_AUDIO MTK_COMBO_CHIP

AUTO_ADD_GLOBAL_DEFINE_BY_NAME_VALUE = LCM_WIDTH LCM_HEIGHT MTK_LCM_PHYSICAL_ROTATION MTK_SHARE_MODEM_SUPPORT MTK_SHARE_MODEM_CURRENT EMMC_CHIP TARGET_BUILD_VARIANT


TARGET_BUILD_VARIANT=user

#
# MTK Build System
#f
BUILD_KERNEL = yes
	# default settings: yes for target; else no (e.g. emulator)
	# candidate settings: yes; no
	# used for MTK build system

BUILD_PRELOADER = no
	# default settings: yes for target; else no (e.g. emulator)
	# candidate settings: yes; no
	# used for MTK build system

BUILD_UBOOT = no
	# default settings: yes for target; else no (e.g. emulator)
	# candidate settings: yes; no
	# used for MTK build system

#CUSTOM_MODEM = jrdsh15_td_ics_tdd128hspa


#
# Customize for PRELOADER
#
CUSTOM_PRELOADER_CUSTOM = custom


#
# Customize for UBOOT
#
CUSTOM_UBOOT_LCM = nt35516_dsi_3P2463

LCM_WIDTH = 540
LCM_HEIGHT = 960

BOOT_LOGO = qhd


#
# Customize for HAL
#
CUSTOM_HAL_AUDIOFLINGER = audio
CUSTOM_HAL_BLUETOOTH = bluetooth
CUSTOM_HAL_CAMERA = camera
CUSTOM_HAL_IMGSENSOR = gc0329_yuv hi704_yuv mt9p017_mipi_raw s5k4e1ga_mipi_raw 
CUSTOM_HAL_EEPROM = dummy_eeprom
CUSTOM_HAL_FLASHLIGHT = constant_flashlight
#CUSTOM_HAL_LENS = FM50AF MT9P017AF dummy_lens
CUSTOM_HAL_LENS = fm50af mt9p017af dummy_lens
#CUSTOM_HAL_LENS = mt9p017af #2
#CUSTOM_HAL_MAIN_LENS = FM50AF
CUSTOM_HAL_MAIN_LENS = fm50af
#CUSTOM_HAL_MAIN_LENS = mt9p017af #2
CUSTOM_HAL_MAIN_BACKUP_LENS = 
#CUSTOM_HAL_SUB_LENS = MT9P017AF
CUSTOM_HAL_SUB_LENS = mt9p017af
#CUSTOM_HAL_SUB_LENS = dummy_lens
CUSTOM_HAL_SUB_BACKUP_LENS =
CUSTOM_HAL_MAIN_IMGSENSOR = mt9p017_mipi_raw
CUSTOM_HAL_MAIN_BACKUP_IMGSENSOR = 
CUSTOM_HAL_SUB_IMGSENSOR = gc0329_yuv
CUSTOM_HAL_SUB_BACKUP_IMGSENSOR = 
CUSTOM_HAL_COMBO = mt6620
CUSTOM_HAL_ANT = mt6620_ant_m3

#
# Customize for Kernel
#
CUSTOM_KERNEL_HEADSET = accdet

CUSTOM_KERNEL_FM = mt6620

CUSTOM_KERNEL_CAMERA = camera
CUSTOM_KERNEL_IMGSENSOR = gc0329_yuv hi704_yuv mt9p017_mipi_raw s5k4e1ga_mipi_raw
MT9P017_MIPI_RAW = yes
#S5K4E1FX_MIPI_RAW = yes
S5K4E1GA_MIPI_RAW = yes
HI704_YUV = yes
GC0329_YUV = yes

#CUSTOM_KERNEL_LENS = FM50AF MT9P017AF dummy_lens
CUSTOM_KERNEL_LENS = fm50af mt9p017af dummy_lens
#CUSTOM_KERNEL_LENS = mt9p017af #2

CUSTOM_KERNEL_BATTERY = battery

CUSTOM_KERNEL_SOUND = sound

CUSTOM_KERNEL_CORE = src
	# default settings: src
	# candidate settings: src
	# board configuation. .

CUSTOM_KERNEL_DCT = dct

CUSTOM_KERNEL_EEPROM = dummy_eeprom

CUSTOM_KERNEL_FLASHLIGHT = constant_flashlight

CONSTANT_FLASHLIGHT = yes

CUSTOM_KERNEL_KPD = kpd
	# default settings: kpd
	# candidate settings: kpd
	# For Keypad

CUSTOM_KERNEL_LCM = nt35516_dsi_3P2463
MTK_DITHERING_SUPPORT = yes
# set this value as 90 if the lcm is physically rotated on the device
MTK_LCM_PHYSICAL_ROTATION = 0


CUSTOM_KERNEL_LEDS = mt65xx

#CUSTOM_KERNEL_MAIN_LENS = FM50AF 
CUSTOM_KERNEL_MAIN_LENS = fm50af
#CUSTOM_KERNEL_MAIN_LENS = mt9p017af #2

CUSTOM_KERNEL_MAIN_BACKUP_LENS = 

#CUSTOM_KERNEL_SUB_LENS = MT9P017AF
CUSTOM_KERNEL_SUB_LENS = mt9p017af
#CUSTOM_KERNEL_SUB_LENS=dummy_lens

CUSTOM_KERNEL_SUB_BACKUP_LENS =

#CUSTOM_KERNEL_MAIN_IMGSENSOR = gc0329_yuv hi704_yuv mt9p017_mipi s5k4elga_mipi_raw
CUSTOM_KERNEL_MAIN_IMGSENSOR = mt9p017_mipi_raw

CUSTOM_KERNEL_MAIN_BACKUP_IMGSENSOR = 

CUSTOM_KERNEL_SUB_IMGSENSOR = gc0329_yuv

CUSTOM_KERNEL_SUB_BACKUP_IMGSENSOR = 

CUSTOM_KERNEL_SOUND = sound

CUSTOM_KERNEL_TOUCHPANEL = gt813

CUSTOM_KERNEL_VIBRATOR = vibrator

CUSTOM_KERNEL_USB = mt6577

CUSTOM_KERNEL_WIFI = mt6620

CUSTOM_KERNEL_RTC = rtc

#MTK_AUTO_DETECT_MAGNETOMETER = yes
CUSTOM_KERNEL_MAGNETOMETER = akm8975 dummy
#CUSTOM_KERNEL_MAGNETOMETER = yamaha530 dummy

#MTK_AUTO_DETECT_ACCELEROMETER = yes
#CUSTOM_KERNEL_ACCELEROMETER = bma250_auto dummy
CUSTOM_KERNEL_ACCELEROMETER = bma250 dummy

CUSTOM_KERNEL_ALSPS = tmd2771 dummy

EVB = no
GEMINI = yes
MTK_GEMINI_ENHANCEMENT = yes
MTK_MODEM_SUPPORT = modem_3g
MTK_GEMINI_3G_SWITCH = yes
MTK_SHARE_MODEM_SUPPORT = 2
MTK_SHARE_MODEM_CURRENT = 2

MTK_FD_SUPPORT = yes

# HQ_PROJECT_A61P allows to use batteries up to 2000mAh
HQ_PROJECT_A61P_HUAWEI = yes

# HQ_CHARGER_FOR_HUAWEI enables temperature control for battery charging and more strong current
HQ_CHARGER_FOR_HUAWEI = yes

# USB CD-ROM
MTK_BICR_SUPPORT = yes

# Force enable higher CPU frequencies
#MTK_CPU_TEST_MODE_FORCE = yes

# When set to yes the ENGINEERING mode is DISABLED
USER_BUILD_KERNEL = yes

HAVE_AEE_FEATURE = yes
HAVE_APPC_FEATURE = no
HAVE_MATV_FEATURE = no

MTK_CHIP_VER = S01
MTK_PLATFORM = MT6577

MTK_MASS_STORAGE = yes
MTK_MULTI_STORAGE_SUPPORT = yes
MTK_EMMC_SUPPORT = yes
MTK_EMMC_SUPPORT_OTP = no
EMMC_CHIP = 4
MTK_2SDCARD_SWAP=yes
MTK_SD_REINIT_SUPPORT=yes

MTK_TVOUT_SUPPORT = no
MTK_SENSOR_SUPPORT = yes

MTK_BT_SUPPORT = yes
MTK_BT_CHIP = MTK_MT6620
MTK_BT_21_SUPPORT=yes
MTK_BT_30_HS_SUPPORT=yes
MTK_BT_30_SUPPORT=yes
MTK_BT_40_LE_STANDALONE=no
MTK_BT_40_SUPPORT=yes
MTK_BT_CHIP=MTK_MT6628
MTK_BT_FM_OVER_BT_VIA_CONTROLLER=no
MTK_BT_POWER_EFFICIENCY_ENHANCEMENT=yes
MTK_BT_PROFILE_A2DP=yes
MTK_BT_PROFILE_AVRCP=yes
MTK_BT_PROFILE_AVRCP13=no
MTK_BT_PROFILE_AVRCP14=yes
MTK_BT_PROFILE_BIP=yes
MTK_BT_PROFILE_BPP=yes
MTK_BT_PROFILE_DUN=yes
MTK_BT_PROFILE_FTP=yes
MTK_BT_PROFILE_HFP=yes
# CHUER. DATE20121029 #
#MTK_BT_PROFILE_HIDH=yes
MTK_BT_PROFILE_HIDH=no
MTK_BT_PROFILE_MANAGER=yes
MTK_BT_PROFILE_MAPC=yes
MTK_BT_PROFILE_MAPS=yes
MTK_BT_PROFILE_OPP=yes
MTK_BT_PROFILE_PAN=yes
MTK_BT_PROFILE_PBAP=yes
MTK_BT_PROFILE_PRXM=no
MTK_BT_PROFILE_PRXR=no
MTK_BT_PROFILE_SIMAP=yes
MTK_BT_PROFILE_SPP=yes
MTK_BT_PROFILE_TIMEC=no
MTK_BT_PROFILE_TIMES=no
MTK_BT_SUPPORT=yes

MTK_FM_SUPPORT = yes
MTK_FM_CHIP = MT6620_FM

MTK_WLAN_SUPPORT = yes
MTK_WAPI_SUPPORT = yes
MTK_GPS_SUPPORT = yes
MTK_GPS_CHIP=MTK_GPS_MT6620
MTK_YGPS_APP=yes
MTK_AGPS_APP=yes

MTK_M4U_SUPPORT = yes

MTK_COMBO_CHIP = MT6620E3

# added qus1 {
CUSTOM_KERNEL_CAM_CAL=dummy_eeprom
CUSTOM_HAL_CAM_CAL=dummy_eeprom
# }

